import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { CustomProvider } from "./custom-provider";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "YeraPos",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Analytics />
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
};

export default RootLayout;
